#ifndef __errorno_H__
#define __errorno_H__


typedef enum _eCloudAccessErrorCode
{
    ERROR_CODE_SUCCESS,
    ERROR_CODE_INITIAL_FAIL,
    ERROR_CODE_USER_NOTEXIST,
    ERROR_CODE_USER_EXIST,
    ERROR_CODE_CREATE_USER_FAIL,
    ERROR_CODE_USER_MAX,
    ERROR_CODE_USER_GET_TOKEN_ERR,
    ERROR_CODE_USER_AUTH_FAIL,
    ERROR_CODE_AUTH_FAIL,
    ERROR_CODE_USER_END = 0x00fff,

    ERROR_CODE_WRITE_ERROR_START = 0x01000,
    ERROR_CODE_WRITE_ERROR,
    ERROR_CODE_WRITE_POOL_FULL,
    ERROR_CODE_WRITE_CREATE_DIR = 0x01100,
    ERROR_CODE_WRITE_CREATE_DIR_PATH_ERR,
    ERROR_CODE_WRITE_CREATE_FILE_ERR,
    ERROR_CODE_WRITE_CREATE_FILE_PATH_ERR,
    ERROR_CODE_WRITE_CREATE_FILE_EXIST_ERR,
    ERROR_CODE_WRITE_CREATE_FILE_NAME_ERR,
    ERROR_CODE_WRITE_CREATE_FILE_NAME_TOO_LONG,

    ERROR_CODE_DELETE_FILE_ERROR = 0x01200,
    ERROR_CODE_DELETE_FILE_NOT_EXIST,
    ERROR_CODE_DELETE_FILE_READ_ONLY,
    ERROR_CODE_DELETE_DIR_ERROR = 0x01300,
    ERROR_CODE_DELETE_DIR_PATH_ERR,
    ERROR_CODE_RENAME_ERROR = 0x01400,
    ERROR_CODE_RENAME_PATH_NO_EXIST = 0x01401,
    ERROR_CODE_RENAME_FILE_NOT_EXIST,
    ERROR_CODE_WRITE_ERROR_END = 0x01fff,

    ERROR_CODE_READ_ERROR_START = 0x02000,
    ERROR_CODE_READ_ERROR,
    ERROR_CODE_READ_ERROR_PATH,
    ERROR_CODE_READ_DIR =  0x02100,
    ERROR_CODE_READ_DIR_PATH_ERR,
    ERROR_CODE_READ_ERROR_END = 0x02fff,

    ERROR_CODE_CA_ERROR_UID_NOT_EXIST = 0x0f000,
    ERROR_CODE_CA_OID_NOT_EXIST,
    ERROR_CODE_CA_INPUT_METADATA_NOT_EXIST,
    ERROR_CODE_CA_INPUT_PATH_FORMAT_ERROR,

    ERROR_CODE_METADATA_ERROR = 0x30000,
    ERROR_CODE_METADATA_FORMAT_ERROR,
    ERROR_CODE_METADATA_NOT_EXIST,
    ERROR_CODE_METADATA_UID_NOT_EXIST,
    ERROR_CODE_METADATA_INPUT_ERROR_is_file,
    ERROR_CODE_METADATA_INPUT_PATH_ERR,
    ERROR_CODE_METADATA_INPUT_OID,
    ERROR_CODE_METADATA_READ_MD_FILE,

    ERROR_CODE_DCMDATA_ERROR = 0x40000,
    ERROR_CODE_DCMDATA_INPUT_PATH_ERR,

    ERROR_CODE_LKM_ERROR = 0x50000,
    ERROR_CODE_LKM_W_ERROR,
    ERROR_CODE_LKM_R_ERROR,
    ERROR_CODE_LKM_INPUT_FORMAT,
    ERROR_CODE_LKM_DESTROY,
    ERROR_CODE_LKM_INTERNAL_ERR,
    ERROR_CODE_LKM_INTERNAL_ERR_GET_NODE_LOCK_FAIL,
    ERROR_CODE_LKM_INTERNAL_SEARCH_NOT_FOUND,

    ERROR_CODE_GENERAL_ERROR_START = 0xf0000,
    ERROR_CODE_GENERAL_ERROR,
    ERROR_CODE_NETWORK_ERROR,
    ERROR_CODE_SERVER_RETURN_FORMAT_ERROR,
    ERROR_CODE_NULL_POINT_EXCEPTION,
    ERROR_CODE_NONEXPECT_ERROR,
    ERROR_CODE_READ_BIG_FILE,
    ERROR_CODE_CNT,

}eCloudAccessErrorCode;

#endif

